#!/bin/sh

if [ "${0%setqt}" != "$0" ]; then
    
echo ''
echo "Run '. ./setqt' to set Qt3 environment"
echo ''

else

echo ''
echo 'Setting Qt3 environment'
echo ''
export QTDIR=~/Programming/qt-x11-free-3.3.8b
export QMAKESPEC=linux-g++-64
export PATH=$QTDIR/bin:$PATH

fi

# Change the values as needed
# see the Qt docs for details

