#!/bin/sh

if [ "${0%setqt}" != "$0" ]; then
    
echo ''
echo "Run '. ./setqt' to set Qt3 environment"
echo ''

else

echo ''
echo 'Setting Qt3 environment'
echo ''
export QTDIR=/usr/lib/qt3
export QMAKESPEC=linux-g++
export PATH=$PATH:/usr/lib/qt3/bin

fi

# Change the values as needed
# see the Qt docs for details

